# .github/workflows/main.yml
name: Hello World CI

on: 
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run hello.py
      run: |
        python hello.py
